"""Unit tests for app.memory.trade_outcome_rag and the
ConsensusComparator historical-edge addition."""

from __future__ import annotations

from datetime import UTC, datetime

import pytest

from app.agents.consensus_compare import ConsensusComparator
from app.memory.rag_store import RAGStore
from app.memory.trade_outcome_rag import (
    TRADE_OUTCOME_EVENT_PREFIX,
    TRADE_OUTCOME_SOURCE,
    TradeOutcomeIndexer,
    _format_trade_text,
    filter_trade_outcomes,
    parse_outcome_from_body,
)


@pytest.fixture
def rag(tmp_path):
    """Rag."""
    return RAGStore(tmp_path)


def _trade(
    *,
    trade_id: str,
    ticker: str,
    direction: str,
    pnl_pct: float,
    detector: str = "double_top",
    tier: str = "A",
    regime: str = "trending",
    magnitude: float = 0.7,
    exit_ts: datetime | None = None,
    rationale: str = "test trade",
    source_strategy: str = "TA",
    alpha_vs_imoex_pct: float = 0.5,
):
    """Trade."""
    return {
        "trade_id": trade_id,
        "ticker": ticker,
        "direction": direction,
        "exit_ts": (
            exit_ts.isoformat() if exit_ts is not None else datetime.now(tz=UTC).isoformat()
        ),
        "entry_ts": datetime.now(tz=UTC).isoformat(),
        "pnl_pct": pnl_pct,
        "pnl_rub": pnl_pct * 1000.0,
        "detector": detector,
        "tier": tier,
        "magnitude": magnitude,
        "hmm_regime_at_entry": regime,
        "rationale": rationale,
        "exit_reason": "take_profit" if pnl_pct > 0 else "stop_loss",
        "source_strategy": source_strategy,
        "alpha_vs_imoex_pct": alpha_vs_imoex_pct,
        "expected_rr": 2.0,
        "actual_rr": 1.5 if pnl_pct > 0 else -0.5,
        "holding_min": 60.0,
    }


@pytest.mark.asyncio
async def test_indexer_writes_records_to_rag(rag):
    """Test indexer writes records to rag."""
    indexer = TradeOutcomeIndexer(rag)
    analysis = {
        "date": "2026-05-26",
        "trades": [
            _trade(trade_id="t1", ticker="SBER", direction="BUY", pnl_pct=1.2),
            _trade(trade_id="t2", ticker="GAZP", direction="BUY", pnl_pct=-0.8),
            _trade(trade_id="t3", ticker="SBER", direction="BUY", pnl_pct=2.1),
        ],
    }
    n = await indexer.index_daily_trades("2026-05-26", analysis)
    assert n == 3
    assert len(rag) == 3
    stats = indexer.stats()
    assert stats["indexed"] == 3
    assert stats["failed"] == 0


@pytest.mark.asyncio
async def test_indexer_idempotent_on_trade_id(rag):
    """Re-indexing the same trade_id updates instead of duplicating."""
    indexer = TradeOutcomeIndexer(rag)
    tr = _trade(trade_id="dup", ticker="SBER", direction="BUY", pnl_pct=1.0)
    await indexer.index_daily_trades("2026-05-26", {"trades": [tr]})
    await indexer.index_daily_trades("2026-05-26", {"trades": [tr]})
    assert len(rag) == 1


@pytest.mark.asyncio
async def test_indexer_metadata_carries_outcome_marker(rag):
    """Test indexer metadata carries outcome marker."""
    indexer = TradeOutcomeIndexer(rag)
    await indexer.index_daily_trades(
        "2026-05-26",
        {
            "trades": [_trade(trade_id="m1", ticker="LKOH", direction="BUY", pnl_pct=1.5)],
        },
    )
    results = rag.search("LKOH BUY trending double_top tier A", tickers=["LKOH"], top_k=3)
    assert results
    top = results[0]
    assert top["event_id"].startswith(TRADE_OUTCOME_EVENT_PREFIX)
    assert top["source"] == TRADE_OUTCOME_SOURCE
    parsed_body = parse_outcome_from_body(top["body"])
    assert parsed_body.get("outcome") == "win"
    assert parsed_body.get("type") == "trade_outcome"
    assert parsed_body.get("detector") == "double_top"


@pytest.mark.asyncio
async def test_indexer_filter_trade_outcomes_keeps_only_post_mortems(rag):
    """Test indexer filter trade outcomes keeps only post mortems."""
    rag.add_news(
        event_id="news_1",
        text="Сбербанк увеличил дивиденды",
        ts_utc=datetime.now(tz=UTC),
        tickers=["SBER"],
        source="rss",
        source_tier="A",
        headline="news",
        body="",
    )
    indexer = TradeOutcomeIndexer(rag)
    await indexer.index_daily_trades(
        "2026-05-26",
        {
            "trades": [_trade(trade_id="t_only", ticker="SBER", direction="BUY", pnl_pct=1.5)],
        },
    )
    results = rag.search("Сбербанк дивиденды", tickers=["SBER"], top_k=10)
    assert len(results) >= 2
    outcomes_only = filter_trade_outcomes(results)
    assert all(r["source"] == TRADE_OUTCOME_SOURCE for r in outcomes_only)
    assert len(outcomes_only) == 1
    assert outcomes_only[0]["event_id"].startswith(TRADE_OUTCOME_EVENT_PREFIX)


def test_parse_outcome_from_body_roundtrips():
    """Body payload generated by the indexer can be parsed back."""
    body = (
        "type=trade_outcome; date=2026-05-26; outcome=win; ticker=SBER; "
        "direction=BUY; detector=double_top; tier=A; magnitude=0.7200; "
        "pnl_pct=1.2300; holding_min=60"
    )
    parsed = parse_outcome_from_body(body)
    assert parsed["type"] == "trade_outcome"
    assert parsed["outcome"] == "win"
    assert parsed["ticker"] == "SBER"
    assert parsed["detector"] == "double_top"
    assert parsed["magnitude"] == pytest.approx(0.72, abs=1e-3)
    assert parsed["pnl_pct"] == pytest.approx(1.23, abs=1e-3)
    assert parsed["holding_min"] == 60


def test_parse_outcome_from_body_empty():
    """Test parse outcome from body empty."""
    assert parse_outcome_from_body("") == {}
    assert parse_outcome_from_body(None) == {}  # type: ignore[arg-type]


def test_format_trade_text_has_query_keywords():
    """The text we index must contain the keywords used in queries."""
    tr = _trade(
        trade_id="x",
        ticker="SBER",
        direction="BUY",
        pnl_pct=1.0,
        detector="double_top",
        tier="A",
        regime="trending",
        magnitude=0.65,
    )
    text = _format_trade_text(tr)
    assert "SBER" in text
    assert "BUY" in text
    assert "double_top" in text
    assert "tier A" in text
    assert "trending" in text


@pytest.mark.asyncio
async def test_get_similar_past_trades_returns_only_outcomes(rag):
    """ConsensusComparator.get_similar_past_trades filters out news."""
    rag.add_news(
        event_id="news_x",
        text="Сбербанк отчитался",
        ts_utc=datetime.now(tz=UTC),
        tickers=["SBER"],
        source="rss",
        source_tier="A",
        headline="news",
        body="",
    )
    indexer = TradeOutcomeIndexer(rag)
    await indexer.index_daily_trades(
        "2026-05-26",
        {
            "trades": [
                _trade(trade_id="win1", ticker="SBER", direction="BUY", pnl_pct=1.5),
                _trade(trade_id="loss1", ticker="SBER", direction="BUY", pnl_pct=-1.0),
            ],
        },
    )
    comp = ConsensusComparator(rag=rag, consensus_today={}, llm_backend="polza")
    results = await comp.get_similar_past_trades(
        ticker="SBER",
        current_setup={
            "direction": "BUY",
            "hmm_regime": "trending",
            "detector": "double_top",
            "tier": "A",
        },
        k=5,
    )
    assert all(r["source"] == TRADE_OUTCOME_SOURCE for r in results)
    assert len(results) >= 1
    assert all("parsed_outcome" in r for r in results)
    outcomes = [r["outcome"] for r in results]
    assert set(outcomes) <= {"win", "loss", "flat"}


def test_historical_edge_multiplier_high_winrate():
    """≥70% WR → 1.3x bonus."""
    similar = [
        {"outcome": "win"},
        {"outcome": "win"},
        {"outcome": "win"},
        {"outcome": "loss"},
    ]
    mult = ConsensusComparator.historical_edge_multiplier(similar)
    assert mult == pytest.approx(1.3)


def test_historical_edge_multiplier_low_winrate():
    """≤30% WR → 0.7x penalty."""
    similar = [
        {"outcome": "loss"},
        {"outcome": "loss"},
        {"outcome": "loss"},
        {"outcome": "win"},
    ]
    mult = ConsensusComparator.historical_edge_multiplier(similar)
    assert mult == pytest.approx(0.7)


def test_historical_edge_multiplier_neutral_mid_winrate():
    """50% WR or insufficient samples → 1.0."""
    mid = [{"outcome": "win"}, {"outcome": "loss"}, {"outcome": "win"}, {"outcome": "loss"}]
    assert ConsensusComparator.historical_edge_multiplier(mid) == pytest.approx(1.0)
    one = [{"outcome": "win"}]
    assert ConsensusComparator.historical_edge_multiplier(one) == pytest.approx(1.0)
    assert ConsensusComparator.historical_edge_multiplier([]) == pytest.approx(1.0)


@pytest.mark.asyncio
async def test_apply_historical_edge_scales_magnitude(rag):
    """End-to-end: index 3 wins → comparator boosts magnitude."""
    indexer = TradeOutcomeIndexer(rag)
    await indexer.index_daily_trades(
        "2026-05-26",
        {
            "trades": [
                _trade(trade_id="w1", ticker="SBER", direction="BUY", pnl_pct=1.2),
                _trade(trade_id="w2", ticker="SBER", direction="BUY", pnl_pct=1.5),
                _trade(trade_id="w3", ticker="SBER", direction="BUY", pnl_pct=0.8),
                _trade(trade_id="l1", ticker="SBER", direction="BUY", pnl_pct=-0.5),
            ],
        },
    )
    comp = ConsensusComparator(rag=rag, consensus_today={}, llm_backend="polza")
    new_mag, debug = await comp.apply_historical_edge(
        ticker="SBER",
        current_setup={
            "direction": "BUY",
            "hmm_regime": "trending",
            "detector": "double_top",
            "tier": "A",
        },
        magnitude=0.5,
        k=10,
    )
    assert debug["wins"] == 3
    assert debug["losses"] == 1
    assert debug["multiplier"] == pytest.approx(1.3)
    assert new_mag == pytest.approx(0.65, abs=1e-3)


@pytest.mark.asyncio
async def test_get_similar_past_trades_handles_empty(rag):
    """Test get similar past trades handles empty."""
    comp = ConsensusComparator(rag=rag, consensus_today={}, llm_backend="polza")
    out = await comp.get_similar_past_trades(
        ticker="SBER",
        current_setup={
            "direction": "BUY",
            "hmm_regime": "trending",
            "detector": "double_top",
            "tier": "A",
        },
    )
    assert out == []
